name: flutter_security_checker
description: This plugin provides the ability to verify rooting and integrity on Android and iOS platforms.
version: 2.0.0
homepage: https://github.com/Dev-hwang/flutter_security_checker

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.flutter_security_checker
        pluginClass: FlutterSecurityCheckerPlugin
      ios:
        pluginClass: FlutterSecurityCheckerPlugin
